name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
      - "master"
  push:
    branches:
      - "*.x"
      - "master"
  schedule:
    - cron: "42 9 * * 1"

jobs:
  psalm:
    name: "Static Analysis"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-"

      - name: "Install dependencies with composer"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-dist"

      - name: "Run psalm"
        run: "vendor/bin/psalm --long-progress --output-format=github --report=psalm.sarif --php-version=${{ matrix.php-version }}"

      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v1
        continue-on-error: true
        with:
          sarif_file: psalm.sarif

  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        deps:
          - "--prefer-lowest"
          - ""
        coverage:
          - "false"
        include:
          - php-version: "8.1"
            deps: ""
            coverage: "true"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "bcmath gmp"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-"

      - name: "Install dependencies with composer"
        run: "composer update --no-interaction --no-progress --no-suggest --prefer-dist ${{ matrix.deps }}"

      - name: "Run PHPCS check"
        run: "composer cs-check"
        if: "${{ matrix.coverage == 'true' }}"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit -c phpunit.xml.dist"
        if: "${{ matrix.coverage != 'true' }}"

      - name: "Run PHPUnit with coverage"
        run: "vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.xml"
        if: "${{ matrix.coverage == 'true' }}"

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage-report.xml
        if: "${{ matrix.coverage == 'true' }}"